### ISSUE TITLE
Would be nice to get a junk when enemy's weapon is destroyed

### ISSUE THREAD

**Issue by kkolyan** [phobos2077/fo2_ecco#6]
I partially agree that weapon destruction could be good for balance, as weapon scavenging is too viable in vanilla, making too much inventory management and distracting attention from other ways to earn money like caravans.

But from the other side I can't help but catch myself on frustration when I seek corpses and see nothing there. Probably, few pieces of junk (proportional to original weapon weight) will handle it well, also making easier (I mean easier in terms of inventory management, not profit) getting some money from combats.

**Comment by phobos2077** [comment]
I'm not sure about junk for money:

- Loot in the game is plenty anyway, especially as you start to search those underground facilities. And it's not like all weapons are destroyed - only 50% of them, so there's not a real need to "live on scavenging". It's not a survival game, in that you don't consume as much. Weapons and armor never wear out, you don't have to eat, drink, build shelters, etc. So there's no such thing as "living off" in this game. At some point you eventually have a lot of money and loot and only limitation is ability to find that certain weapon you want, or crafting some special ammo.
- I don't want to clutter the inventory with too many new items. EcCo already added a bunch of stuff and with traps and crafting components, using Inventory Filter or similar mod becomes a necessity. But in principle, I small number of those items could be added, since the game already has that.

When working on 0.9, I thought about scaling down the scope of the mod, removing or changing everything that does "change for the sake of change", going as vanilla as possible. So any new idea should be bound to this vision.

**Comment by Yi-AXEL** [comment]
Personally, I think the idea of spawning some junks on the corpse whose gun is destroyed might be a good one logic-wise and gameplay-wise.
Logically speaking, when the gun is destroyed by the force of an attack, it will be broken down into parts, and the parts won't simply disappear.
Also, for the perspective of gameplay, the junks dropped might be of use for sell or, if a repair expertise is within disposal, be used as crude materials.
